### ISSUE TITLE
License file is misspelled

### ISSUE THREAD

**Issue by muntact** [Raynos/xtend#35]
Just a heads up your license file is mis-spelled 'licence' and is therefore your license isn't discovered properly by nlf (https://www.npmjs.com/package/nlf)

**Comment by roobie** [comment]
"Licence" is a correct alternative spelling of the word, cf. [grammarist](http://grammarist.com/spelling/licence-license/). I'd propose filing a bug with `nlf`, since there are probably many libraries using this alternative spelling.

**Comment by muntact** [comment]
You're right, the spelling you use is correct in the context that it is not a verb. A colleague pointed out to me that i

**Comment by muntact** [comment]
sorry, accidentally closed the issue. Hope you don't mind as it does appear to have come to an action outside of this repo :)

**Comment by roobie** [comment]
Indeed! As can be seen [here](https://github.com/iandotkelly/nlf/search?utf8=%E2%9C%93&q=licence)

Also, I'm sorry for nitpicking, but for completeness sake, "licence" is only correct when used as a noun. Used as a verb, it should always be "license" as in "It was licensed by the authority". So PR #31 Should perhaps be merged, still.

**Comment by muntact** [comment]
Perhaps? i know that nlf has implemented a fix to find the non american spelling; however i am not sure if yarn which added licence finding as a feature will find the alternate spelling?
